name: "godot-ci build"
on:
  pull_request:
    branches: [alpha, beta]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: pong
  PROJECT_PATH: . # NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` to ".".

jobs:
  build:
    strategy:
      matrix:
        target-platform:
          - { os: "Windows Desktop", build_dir: "windows", extension: "exe" }
          - { os: "Linux/X11", build_dir: "linux", extension: "x86_64" }
          - { os: "macOS", build_dir: "mac", extension: "zip" }
          - { os: "Android Debug", build_dir: "android", extension: "apk" }
    name: ${{ matrix.target-platform.os }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Setup Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Setup Godot Config
        if: matrix.target-platform.os == "Windows Desktop" || matrix.target-platform.os == "Android Debug"
        run: |
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
      - name: Setup Debug Keystore
        if: matrix.target-platform.os == "Android Debug"
        run: mv /root/debug.keystore ~/.local/share/godot/debug.keystore
      - name: ${{ matrix.target-platform.os }} Build
        run: |
          mkdir -v -p build/${{ matrix.target-platform.build_dir }}
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release ${{ matrix.target-platform.os }} \
          "$EXPORT_DIR/${{ matrix.target-platform.build_dir }}/$EXPORT_NAME.${{ matrix.target-platform.extension }}"